apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name:  postgres-cnt
        image: postgres:13.3
        ports:
        - containerPort: 5432
        env:
            - name: POSTGRES_USER
              value:  postgres
            - name: POSTGRES_PASSWORD
              value:  "1234"
            - name: POSTGRES_DB
              value: suppliers_db
